apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # App of Apps Application
  - application.yaml

  # Infrastructure services
  - gitea/argocd/gitea.yaml

  # Applications and services
  - homer/argocd/homer.yaml
  - docusaurus/argocd/docusaurus.yaml
  - code-server/argocd/code-server.yaml
  - umami/argocd/umami.yaml
  - kubernetes-dashboard/argocd/kubernetes-dashboard.yaml

  # Backup jobs
  - backup/gitea-backup-cronjob.yaml
  - backup/gitea-minio-setup-job.yaml
